---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.1.0
    hostname: kafka
    ports:
      - '9092:9092'
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,state.change.logger=INFO,kafka.coordinator.group=WARN,kafka.cluster=WARN,kafka.log=WARN,kafka.server=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka/broker/kafka-logs:/kafka
      - ./kafka/broker/logs:/logs
      - ./kafka/broker/data:/data

  solar-panel-app:
    image: rickerlyman/solar-panel-emulator:latest
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092

  streaming-app:
    image: rickerlyman/streaming-app:latest
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092

  weather-provider:
    image: rickerlyman/weather-provider:latest
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
